name: Basic Workflowon:
  workflow_dispatch: # Allows manual triggeringjobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello, GitHub Actions!"